### PR TITLE
Rails 5.1.4 Upgrade

### PR DESCRIPTION
**Pull request by sebasjimenez10**
Hey @bloggervista!

So I was able to upgrade the app and run it locally without a problem. Due to the lack of testing I would suggest you clone my fork and run it, just to make sure everything runs as expected.

After that you should be good to merge it into master.

Hope this helps!

### CODE REVIEW

**Comment by bloggervista** [comment]
Thank you so much. I hope you won't mind writing your name in contributor list. Seems like there is no breaking change. Yeah I don't have good lappy to write unit and integration test. And this upgrade seems to be fine so will merge it.

**Comment by bloggervista** [comment]
Thanks bro but before this can we fix this travis issue. https://travis-ci.org/bloggervista/Bee-Connect/builds/292096980?utm_source=github_status&utm_medium=notification

**Comment by sebasjimenez10** [comment]
@bloggervista yeah I saw the issues on travis and seems to be the migrations versioning. I already updated and pushed some changes to fix that.

**Comment by bloggervista** [comment]
Thanks +1 for editing readme files also :)

**Comment by sebasjimenez10** [comment]
@bloggervista also added myself to the contributors list 😄

**Pull request merged**
